# techonologies Node, react, nextjs, tailwind, typescript
# the-core-react-tailwind
# docker build -t react-nextjs-tailwind .
FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk add nodejs-current npm
RUN apk add git
WORKDIR /home/app
RUN npm init --yes
RUN npm install -D tailwindcss
RUN npm install next@latest react@latest react-dom@latest
RUN npm install -D prettier prettier-plugin-tailwindcss
RUN npm install react-i18next i18next --save
RUN npm install react-icons --save
RUN npm i axios
RUN npm install zustand
RUN npm i react-error-boundary
RUN npm audit fix --force

RUN apk add --no-cache tzdata
RUN apk add --no-cache su-exec
RUN set -ex && apk --no-cache add sudo
  
ENV TZ="Europe/Athens"
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV NODE_ENV=development
ENV CI=true

WORKDIR /home/app