import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

import LocalesDropdown from "./components/organisms/LocalesDropdown"

// const LocalesDropdown = dynamic(() => import("./components/organisms/LocalesDropdown"))

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen w-screen overflow-hidden">
        <LocalesDropdown/>
        {children}
      </body>
    </html>
  );
}
